apiVersion: tagesApp/v0.1.0
kind: Ingress
metadata:
  name: tages-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: tages-k8s-ingress
  rules:
  - http:
      paths:
      - path: /s1
        pathType: Prefix
        backend:
          service:
            name: service-1
            port:
              number: 8080
      - path: /s2
        pathType: Prefix
        backend:
          service:
            name: service-2
            port:
              number: 3000
