apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-deployment
  labels:
    app: tages-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tages-k8s
  template:
    metadata:
      labels:
        app: tages-k8s
    spec:
      containers:
      - name: tages-k8s-service-1
        image: wallodya/tages-k8s-service-1
        ports:
        - containerPort: 8080
